github:
  features:
  # Enable issue management
    issues: true
  # Enable projects for project management boards
    projects: true
# Set up mailing list notifications
notifications:
  commits:             doc@openoffice.apache.org
  issues:              doc@openoffice.apache.org
  pullrequests:        doc@openoffice.apache.org
  
  
